"""
LLM-as-Judge Unit Test Quality Evaluation

Double-blind, double-pass pairwise evaluation of LLM-generated unit tests using
Claude as judge. Mitigates position bias by swapping A/B order between passes.

Scoring: 4 criteria × 1-5 Likert (max 20 per pass, 40 total). Equal weighting.
Null-test veto: if Assertions = 1, total score = 1 regardless of other criteria.

Bias detection:
- Position bias: Pass1 winner = A (pos1), Pass2 winner = B (pos1 after swap) -> Invalid
- Stochastic noise: passes disagree AND score variance > 4.0 -> Stochastic_Noise
- Clean judgment: A wins both OR B wins both

Usage:
    python step3_modelling/llm_as_judge.py --predictions_dir TestEval/predictions_realworld_1 --eval_dir evaluation_results_realworld_1 --evaluation_group full_factorial --output_dir TestEval/predictions_judgellm
"""

import argparse
import json
import math
import os
import logging
import glob
import time
import itertools
import hashlib
import numpy as np
import pandas as pd
from tqdm import tqdm
import anthropic
from anthropic import RateLimitError, APIError
from dotenv import load_dotenv
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading

load_dotenv()


LOG_FILE = os.path.join(os.path.dirname(__file__), 'llm_as_judge_logs.log')
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE, mode='a', encoding='utf-8'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


DEFAULT_MODEL = "claude-haiku-4-5-20251001"
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# T=0.1 allows slight variance to test if the reasoning is robust.
JUDGE_TEMPERATURE = 0.1

# Pricing — claude-haiku-4-5 (USD per million tokens)
PRICE_INPUT_PER_M = 0.80
PRICE_OUTPUT_PER_M = 4.00

if not ANTHROPIC_API_KEY:
    raise ValueError("Please set the ANTHROPIC_API_KEY environment variable.")

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
MODEL_NAME = DEFAULT_MODEL

TIE_THRESHOLD = 2.0  # 5% deviation on 40-point double-pass scale

# ---------------------------------------------------------------------------
# Plan Quality Scoring — LLM-as-Judge for step-1 condition outputs
# Methodology: Zheng et al. 2023 (MT-Bench LLM-as-Judge), rubric dimensions
# from Jiang et al. 2023 (Self-planning Code Generation, arXiv:2303.06689),
# 3-anchor calibration approach from Liu et al. 2023 (G-Eval).
# ---------------------------------------------------------------------------

PLAN_QUALITY_SYSTEM_PROMPT = """You are an expert software testing analyst evaluating the quality of
an intermediate reasoning step generated by an AI model. The model was given a Python function and a
target line number, and asked to describe the input condition needed to execute that line.

Score the condition on TWO dimensions (1-5 each):
  COMPLETENESS: Does the condition identify all necessary constraints and edge cases to reach the target line?
  CORRECTNESS:  Is the proposed condition logically valid for this function's actual signature and semantics?

To calibrate your scoring, study these three reference examples before scoring:

--- ANCHOR EXAMPLE 1 (HIGH QUALITY — Completeness 5, Correctness 5) ---
[FUNCTION]
```python
class Solution:
    WEEKDAYS = ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]

    def get_weekday_index(self, weekday: str) -> int:
        try:
            return self.WEEKDAYS.index(weekday.lower())
        except ValueError:
            raise ValueError(f"Invalid weekday name {weekday!r}") from None
```
[TARGET LINE] Line 7: `raise ValueError(f"Invalid weekday name {weekday!r}") from None`
[CONDITION] "To execute line 7, the try block must raise a ValueError at `WEEKDAYS.index(weekday.lower())`.
This happens when `weekday.lower()` is not present in WEEKDAYS. The input must be a string
(so .lower() succeeds) but not a valid weekday name, e.g. weekday='invalidday'."
[SCORES] Completeness 5 — identifies all constraints: input must be str (for .lower()), must not be in
WEEKDAYS, and the except branch must be triggered. Correctness 5 — logically valid; matches the
actual branch condition exactly.

--- ANCHOR EXAMPLE 2 (MEDIUM QUALITY — Completeness 3, Correctness 3) ---
[FUNCTION]
```python
class Solution:
    def get_encoder(self) -> "Encoder":
        # Get the global encoder object. Returns: Encoder
        return global_encoder
```
[TARGET LINE] Line 4: `return global_encoder`
[CONDITION] "To execute line 4, the function get_encoder must reach its termination point without
encountering any further statements. All preceding lines (1-3) must execute successfully and no
exceptions or errors are raised. The variable global_encoder must be defined and accessible within
the scope of the Solution class."
[SCORES] Completeness 3 — identifies that global_encoder must exist but misses that there are NO
preceding conditional lines; the function is a one-liner with no branches. Fails to mention that
global_encoder is None by default and must have been set via set_encoder() first. Correctness 3 —
not wrong, but describes an unconditional path as if it has prerequisites; the prose about "all
preceding lines must execute" is vacuously true and adds no real insight.

--- ANCHOR EXAMPLE 3 (LOW QUALITY — Completeness 1, Correctness 1) ---
[FUNCTION]
```python
class Solution:
    def set_encoder(self, encoder: "Encoder") -> None:
        # Set the global encoder object.
        global global_encoder
        global_encoder = encoder
```
[TARGET LINE] Line 1 (module-level): `from __future__ import annotations`
[CONDITION] "For line 1 to be executed, the script must be run in an environment where Python's
`from __future__ import annotations` can be processed. This typically requires the interpreter to
be invoked with `-X futures` or by importing the module in a way that activates the future."
[SCORES] Completeness 1 — entirely misses the target: line 1 is a module-level import, always
executed when the module loads; no special input condition is needed. The model should have said
"call set_encoder() with any Encoder instance" for the function body. Correctness 1 — logically
invalid; `from __future__ import annotations` is valid in Python 3.7+ with no special flags;
the `-X futures` claim is factually wrong.

Output strictly valid JSON."""

PLAN_QUALITY_TEMPLATE = """[FUNCTION UNDER TEST]
```python
{focal_code}
```

[TARGET LINE TO REACH]
Line {target_line}: `{target_line_content}`

[GENERATED CONDITION (to evaluate)]
{condition_text}

[OUTPUT FORMAT] Return ONLY this JSON:
{{
  "completeness": <integer 1-5>,
  "correctness": <integer 1-5>,
  "reasoning": "<one sentence justifying each score>"
}}"""

# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are a Senior QA Engineer evaluating unit test quality.
Analyze the test design step-by-step against the criteria.

IMPORTANT GUIDELINES:
1. REASONING FIRST: You must output textual reasoning BEFORE assigning scores.
2. PARADIGM AGNOSTIC: Accept different valid testing styles (e.g., Mocking vs. State Verification).
3. CRITICALITY: A test that asserts nothing is worthless, regardless of code cleanliness.

Output strictly valid JSON."""

EVALUATION_TEMPLATE = """
[PROBLEM DESCRIPTION]
{docstring}

[FOCAL METHOD]
```python
{focal_code}
```

[TEST OPTION A]
```python
{code_a}
```

[TEST OPTION B]
```python
{code_b}
```

[EVALUATION CRITERIA - Score each 1-5 points]

1. ROBUSTNESS (Edge cases, boundary values):
   - 5: Excellent - Comprehensive coverage (Empty, None, Negative, Type errors, Boundary limits, multiple edge cases)
   - 4: Good - Multiple edge cases covered with some depth
   - 3: Acceptable - Basic edge cases or happy path with some variation
   - 2: Poor - Only happy path tested with standard valid inputs
   - 1: Very Poor - Minimal/No coverage, missing critical test cases

2. ASSERTION STRENGTH (Verification quality):
   - 5: Excellent - Strong, specific assertions (Exact values, states, specific exception types with messages)
   - 4: Good - Specific assertions covering key behaviors
   - 3: Acceptable - Basic assertions that verify correctness
   - 2: Poor - Weak/Generic (Asserts type only, or 'is not None')
   - 1: Very Poor - Trivial/None (assert True, or no meaningful assertions)

3. READABILITY (Code clarity):
   - 5: Excellent - Professional (Clear naming, AAA pattern, proper setup, well-documented)
   - 4: Good - Clean structure with clear intent
   - 3: Acceptable - Understandable but could be clearer
   - 2: Poor - Messy or unclear structure
   - 1: Very Poor - Obfuscated/Confusing, hard to understand

4. CONCISENESS (Efficiency):
   - 5: Excellent - Highly efficient (Minimal code, no redundancy, elegant)
   - 4: Good - Efficient with minimal unnecessary code
   - 3: Acceptable - Some unnecessary code but functional
   - 2: Poor - Notable redundancy or verbosity
   - 1: Very Poor - Bloated (Excessive redundancy, dead code, unnecessary complexity)

[OUTPUT FORMAT] Return ONLY this JSON:
{{
  "analysis_test_a": "Step-by-step analysis of A...",
  "analysis_test_b": "Step-by-step analysis of B...",
  "comparison_text": "Textual comparison...",
  "test_a_scores": [Robustness, Assertions, Readability, Conciseness],
  "test_b_scores": [Robustness, Assertions, Readability, Conciseness]
}}
"""

class ThreadSafeWriter:
    """Thread-safe file writer for parallel API calls."""
    def __init__(self, filepath):
        self.filepath = filepath
        self.lock = threading.Lock()

    def write(self, data):
        """Write JSON data to file in thread-safe manner."""
        with self.lock:
            with open(self.filepath, 'a', encoding='utf-8') as f:
                f.write(json.dumps(data) + "\n")

def stable_hash(text):
    """
    Creates a stable hash that persists across Python sessions.

    Python's built-in hash() is salted for security and changes between restarts.
    This breaks cache persistence. Used MD5 for stable, deterministic hashing.

    Args:
        text: String to hash
    Returns:
        Hexadecimal hash string (first 16 chars for brevity)
    """
    return hashlib.md5(text.encode('utf-8')).hexdigest()[:16]

def clean_and_parse_json(response_text):
    """Attempts to extract and repair JSON from LLM output."""
    # Try direct parsing
    try:
        return json.loads(response_text)
    except json.JSONDecodeError:
        pass

    def fix_escape_sequences(text):
        """Fix Python-style escape sequences that are invalid in JSON."""
        import re
        # Replace \xHH (hex escape) with a safe placeholder
        # These appear in the LLM's analysis when describing test code strings
        text = re.sub(r'\\x[0-9a-fA-F]{2}', '<hex>', text)

        # Also fix any other invalid escape sequences
        # Valid JSON escapes are: \" \\ \/ \b \f \n \r \t \uXXXX
        # Replace any \<char> where <char> is not a valid JSON escape
        # Keep the backslash but double it to make it literal
        def replace_invalid_escape(match):
            escaped_char = match.group(1)
            # Valid single-char escapes in JSON
            if escaped_char in ['"', '\\', '/', 'b', 'f', 'n', 'r', 't']:
                return match.group(0)  # Keep as-is
            # Unicode escape
            if escaped_char == 'u':
                return match.group(0)  # Keep as-is
            # Invalid escape - double the backslash to make it literal
            return '\\\\' + escaped_char

        text = re.sub(r'\\(.)', replace_invalid_escape, text)
        return text

    # Strategy 1: Extract from ```json markers (most reliable for our case)
    # Look for ```json followed by content, then ```
    # Use negative lookahead to get the LAST ```
    if '```json' in response_text:
        # Find the ```json marker
        json_start = response_text.find('```json')
        if json_start != -1:
            # Start after ```json and any whitespace
            content_start = json_start + 7  # len('```json')
            # Skip leading whitespace/newlines
            while content_start < len(response_text) and response_text[content_start] in ' \t\n\r':
                content_start += 1

            # Find the LAST ``` marker
            last_backticks = response_text.rfind('```', content_start)
            if last_backticks != -1:
                text_content = response_text[content_start:last_backticks].strip()

                # Fix invalid escape sequences before parsing
                text_content = fix_escape_sequences(text_content)

                try:
                    result = json.loads(text_content)
                    # Success - no need to log verbosely
                    return result
                except json.JSONDecodeError as e:
                    # Only log and save on failure
                    logger.warning(f"Strategy 1: Extracted {len(text_content)} chars from ```json block")
                    logger.warning(f"Extracted starts: {text_content[:80]}...")
                    logger.warning(f"Extracted ends: ...{text_content[-80:]}")
                    logger.warning(f"Strategy 1 FAILED: JSON parse error: {e} at position {e.pos if hasattr(e, 'pos') else 'unknown'}")

                    # Save extracted content to debug file
                    debug_dir = os.path.dirname(LOG_FILE)
                    extracted_file = os.path.join(debug_dir, 'strategy1_extracted.json')
                    try:
                        with open(extracted_file, 'w', encoding='utf-8') as f:
                            f.write(text_content)
                        logger.warning(f"Saved Strategy 1 extracted content to {extracted_file}")
                    except Exception as e2:
                        logger.warning(f"Could not save extracted content: {e2}")

    # Strategy 2: Extract JSON object with balanced braces
    # Find first { and match balanced braces
    first_brace = response_text.find('{')
    if first_brace != -1:
        brace_count = 0
        in_string = False
        escape_next = False

        for i in range(first_brace, len(response_text)):
            char = response_text[i]

            if escape_next:
                escape_next = False
                continue

            if char == '\\':
                escape_next = True
                continue

            if char == '"' and not escape_next:
                in_string = not in_string
                continue

            if not in_string:
                if char == '{':
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
                    if brace_count == 0:
                        # Found matching closing brace
                        text_content = response_text[first_brace:i+1]

                        text_content = fix_escape_sequences(text_content)

                        try:
                            result = json.loads(text_content)
                            # Success - no need to log verbosely
                            return result
                        except json.JSONDecodeError as e:
                            # Only log and save on failure
                            logger.warning(f"Strategy 2: Extracted {len(text_content)} chars with balanced braces")
                            logger.warning(f"Strategy 2 FAILED: JSON parse error: {e} at position {e.pos if hasattr(e, 'pos') else 'unknown'}")

                            # Save extracted content to debug file
                            debug_dir = os.path.dirname(LOG_FILE)
                            extracted_file = os.path.join(debug_dir, 'strategy2_extracted.json')
                            try:
                                with open(extracted_file, 'w', encoding='utf-8') as f:
                                    f.write(text_content)
                                logger.warning(f"Saved Strategy 2 extracted content to {extracted_file}")
                            except Exception as e2:
                                logger.warning(f"Could not save extracted content: {e2}")
                        break

    logger.error("ALL STRATEGIES FAILED: Could not extract valid JSON")
    return None

def call_claude_judge(prompt, retries=3):
    """Call LLM with granular error handling and JSON validation."""
    required_keys = ["test_a_scores", "test_b_scores"]
    last_failure_reason = "Unknown"

    for attempt in range(retries):
        try:
            # Rate limiting buffer (reduced for parallel execution - concurrency controlled by ThreadPoolExecutor)
            time.sleep(0.1)

            response = client.messages.create(
                model=MODEL_NAME,
                max_tokens=8192,
                temperature=JUDGE_TEMPERATURE,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}]
            )

            response_text = response.content[0].text

            # Check for truncation (incomplete response)
            stop_reason = response.stop_reason
            if stop_reason == "max_tokens":
                last_failure_reason = f"Response truncated (hit max_tokens limit). Response length: {len(response_text)} chars"
                logger.warning(f"{last_failure_reason} (Attempt {attempt + 1}/{retries})")
                if attempt < retries - 1:
                    time.sleep(2 ** attempt * 2)
                continue

            result = clean_and_parse_json(response_text)

            if result:
                # Validate Keys
                if all(k in result for k in required_keys):
                    return result
                else:
                    last_failure_reason = f"Missing keys: expected {required_keys}, got {list(result.keys())}"
                    logger.warning(f"{last_failure_reason} (Attempt {attempt + 1}/{retries})")
                    if attempt < retries - 1:
                        time.sleep(2 ** attempt * 2)  # Exponential backoff for JSON issues
            else:
                # Check if response ends abruptly (likely truncated)
                ends_cleanly = response_text.rstrip().endswith(('```', '}', ']'))
                # Show both start and end for better debugging
                start_text = response_text[:100] if len(response_text) > 100 else response_text
                end_text = response_text[-100:] if len(response_text) > 100 else response_text
                last_failure_reason = f"JSON parsing failed. Response length: {len(response_text)} chars, ends_cleanly: {ends_cleanly}, starts: {start_text}... ends: ...{end_text}"
                logger.warning(f"{last_failure_reason} (Attempt {attempt + 1}/{retries})")
                # Save full response to debug file for inspection
                if attempt == retries - 1:
                    debug_file = os.path.join(os.path.dirname(LOG_FILE), 'failed_json_response.txt')
                    with open(debug_file, 'w', encoding='utf-8') as f:
                        f.write(response_text)
                    logger.error(f"Saved full failed response to {debug_file} for debugging")
                if attempt < retries - 1:
                    time.sleep(2 ** attempt * 2)  # Exponential backoff for JSON issues

        except RateLimitError as e:
            last_failure_reason = f"Rate Limit: {e}"
            wait_time = 2 ** attempt * 10
            logger.warning(f"Rate Limit Hit. Waiting {wait_time}s... (Attempt {attempt + 1}/{retries})")
            time.sleep(wait_time)

        except APIError as e:
            last_failure_reason = f"API Error: {e}"
            wait_time = 2 ** attempt * 5
            logger.warning(f"Anthropic API Error: {e}. Waiting {wait_time}s... (Attempt {attempt + 1}/{retries})")
            time.sleep(wait_time)

        except Exception as e:
            last_failure_reason = f"Unexpected Error: {e}"
            logger.error(f"Unexpected Error: {e} (Attempt {attempt + 1}/{retries})")
            if attempt == retries - 1: return None
            time.sleep(5)

    logger.error(f"Failed to get valid response after {retries} retries. Last failure: {last_failure_reason}")
    return None

def calculate_weighted_score(raw_scores):
    """Sum criterion scores (Robustness, Assertions, Readability, Conciseness) 1-5 each.

    Null-test veto: if Assertions = 1, returns 1.0 regardless of other scores.
    Max score: 20.0 per pass.
    """
    if len(raw_scores) < 4:
        raw_scores = raw_scores + [1] * (4 - len(raw_scores))  # Default to 1 (Very Poor) for missing scores

    robustness, assertions, readability, conciseness = raw_scores[0], raw_scores[1], raw_scores[2], raw_scores[3]

    if assertions == 1:
        return 1.0

    return robustness + assertions + readability + conciseness

def judge_pair_double_pass(task_id, focal_code, docstring, model_a_name, code_a, model_b_name, code_b):
    """Performs Double-Pass Evaluation with Python-side Weighted Math."""

    # PASS 1: A vs B
    prompt_1 = EVALUATION_TEMPLATE.format(
        docstring=docstring, focal_code=focal_code, code_a=code_a, code_b=code_b
    )
    result_1 = call_claude_judge(prompt_1)
    if not result_1: return None

    # PASS 2: B vs A
    prompt_2 = EVALUATION_TEMPLATE.format(
        docstring=docstring, focal_code=focal_code, code_a=code_b, code_b=code_a
    )
    result_2 = call_claude_judge(prompt_2)
    if not result_2: return None

    # Extracting scores
    scores_1_pos1 = result_1.get("test_a_scores", [1,1,1,1]) # Model A (default to 1 = Very Poor)
    scores_1_pos2 = result_1.get("test_b_scores", [1,1,1,1]) # Model B

    scores_2_pos1 = result_2.get("test_a_scores", [1,1,1,1]) # Model B (Swapped)
    scores_2_pos2 = result_2.get("test_b_scores", [1,1,1,1]) # Model A (Swapped)

    wa_1 = calculate_weighted_score(scores_1_pos1)
    wa_2 = calculate_weighted_score(scores_2_pos2)
    model_a_total = wa_1 + wa_2

    wb_1 = calculate_weighted_score(scores_1_pos2)
    wb_2 = calculate_weighted_score(scores_2_pos1)
    model_b_total = wb_1 + wb_2

    # Determine winner for each pass
    pass1_winner = "A" if (wa_1 - wb_1) > TIE_THRESHOLD else ("B" if (wb_1 - wa_1) > TIE_THRESHOLD else "Tie")
    pass2_winner = "A" if (wa_2 - wb_2) > TIE_THRESHOLD else ("B" if (wb_2 - wa_2) > TIE_THRESHOLD else "Tie")

    bias_status = "None"

    # Calculate score variance between passes for noise detection
    score_variance_a = abs(wa_1 - wa_2)
    score_variance_b = abs(wb_1 - wb_2)
    max_score_variance = max(score_variance_a, score_variance_b)

    # Position 1 bias: A wins pass1 (A in pos1), B wins pass2 (B in pos1 after swap)
    if pass1_winner == "A" and pass2_winner == "B":
        bias_status = "Position_Bias_First"

    # Position 2 bias (rare): B wins pass1 (B in pos2), A wins pass2 (A in pos2 after swap)
    elif pass1_winner == "B" and pass2_winner == "A":
        bias_status = "Position_Bias_Second"

    # Stochastic Noise: Disagreement without positional pattern
    # High variance in scores between passes indicates unreliable judgment
    elif pass1_winner != pass2_winner and max_score_variance > 4.0:  # >4 points difference on 20-point scale
        bias_status = "Stochastic_Noise"

    # If A wins both times OR B wins both times, that's consistent judgment (not bias)
    # Small disagreements (Tie vs narrow win) are acceptable and handled by averaging

    # The winner
    score_diff = abs(model_a_total - model_b_total)
    final_winner = "Tie"
    
    if bias_status != "None":
        final_winner = "Invalid_Bias"
    elif score_diff > TIE_THRESHOLD:
        final_winner = "A" if model_a_total > model_b_total else "B"

    return {
        "task_id": task_id,
        "model_a": model_a_name,
        "model_b": model_b_name,
        "bias_status": bias_status,
        "final_winner_model": final_winner,
        "model_a_total_score": model_a_total,
        "model_b_total_score": model_b_total,
        "score_diff": score_diff,
        # Reliability metrics for noise detection
        "score_variance_a": score_variance_a,
        "score_variance_b": score_variance_b,
        "max_score_variance": max_score_variance,
        "pass1_winner": pass1_winner,
        "pass2_winner": pass2_winner,
        # Raw criterion scores for transparency and post-hoc analysis
        "model_a_scores_pass1": scores_1_pos1,  # [robustness, assertions, readability, conciseness]
        "model_a_scores_pass2": scores_2_pos2,
        "model_b_scores_pass1": scores_1_pos2,
        "model_b_scores_pass2": scores_2_pos1,
        # Reasoning and code for validation
        "reasoning_pass_full": result_1.get("comparison_text", ""),
        "code_a": code_a,
        "code_b": code_b,
        "focal_code": focal_code,
        "docstring": docstring
    }

# ---------------------------------------------------------------------------
# Plan Quality — new functions
# ---------------------------------------------------------------------------

def call_plan_judge(condition_text, focal_code, target_line, target_line_content, retries=3):
    """Score one step-1 condition on Completeness and Correctness (1-5 each).

    Single-pass (not double-pass) because this is absolute scoring, not pairwise.
    Reuses existing retry/backoff and JSON-parsing infrastructure.
    Returns {"completeness": int, "correctness": int, "reasoning": str} or None.
    """
    required_keys = ["completeness", "correctness"]
    prompt = PLAN_QUALITY_TEMPLATE.format(
        focal_code=focal_code,
        target_line=target_line,
        target_line_content=target_line_content,
        condition_text=condition_text,
    )
    last_failure = "Unknown"

    for attempt in range(retries):
        try:
            time.sleep(0.1)
            response = client.messages.create(
                model=MODEL_NAME,
                max_tokens=512,
                temperature=JUDGE_TEMPERATURE,
                system=PLAN_QUALITY_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            if response.stop_reason == "max_tokens":
                last_failure = "Response truncated"
                if attempt < retries - 1:
                    time.sleep(2 ** attempt * 2)
                continue

            result = clean_and_parse_json(response.content[0].text)
            if result and all(k in result for k in required_keys):
                # Clamp scores to valid range
                result["completeness"] = max(1, min(5, int(result["completeness"])))
                result["correctness"]  = max(1, min(5, int(result["correctness"])))
                result.setdefault("reasoning", "")
                return result

            last_failure = f"Missing keys or parse failed: {result}"
            if attempt < retries - 1:
                time.sleep(2 ** attempt * 2)

        except RateLimitError:
            wait = 2 ** attempt * 10
            logger.warning(f"Rate limit — waiting {wait}s (attempt {attempt+1}/{retries})")
            time.sleep(wait)
        except APIError as e:
            wait = 2 ** attempt * 5
            logger.warning(f"API error: {e} — waiting {wait}s (attempt {attempt+1}/{retries})")
            time.sleep(wait)
        except Exception as e:
            logger.error(f"Unexpected error in call_plan_judge: {e}")
            if attempt == retries - 1:
                return None
            time.sleep(5)

    logger.error(f"call_plan_judge failed after {retries} retries. Last: {last_failure}")
    return None


def _extract_target_line_content(focal_code, target_line):
    """Return the source text of a given 1-based line number from focal_code."""
    lines = focal_code.splitlines()
    idx = int(target_line) - 1
    if 0 <= idx < len(lines):
        return lines[idx].strip()
    return ""


def load_conditions(base_dir, evaluation_group="best_configs", eval_dir=None):
    """Load step-1 condition texts for two-step (linecov2_*) files only.

    Returns conditions_data:
        { task_id: { model_name: [
              {"condition_text": str, "target_line": str,
               "eval_status": str, "focal_code": str, "docstring": str},
              ...  (one entry per target line)
          ]}}
    """
    groups = select_evaluation_groups()
    if evaluation_group not in groups:
        raise ValueError(f"Unknown group: {evaluation_group}")

    selected_models = groups[evaluation_group]
    # Only two-step configs have conditions
    two_step_models = [(p, n) for p, n in selected_models if p.startswith("linecov2_")]
    if not two_step_models:
        logger.warning("No two-step (linecov2_*) configs in this group — no conditions to load.")
        return {}

    if eval_dir:
        eval_base_dir = eval_dir
    elif "predictions" in base_dir.lower():
        base_cleaned = base_dir.split(os.sep)[-1] if os.sep in base_dir else base_dir
        if "predictions_realworld" in base_cleaned:
            eval_base_dir = "evaluation_results_realworld"
        elif "predictions_initial" in base_cleaned:
            eval_base_dir = "evaluation_results_initial"
        else:
            eval_base_dir = base_dir.replace("predictions", "evaluation_results")
    else:
        eval_base_dir = base_dir

    conditions_data = {}

    for pattern, friendly_name in two_step_models:
        pred_files = glob.glob(os.path.join(base_dir, "run_1", pattern))
        if not pred_files:
            logger.warning(f"No prediction files for {friendly_name}: {pattern}")
            continue

        eval_pattern = pattern.replace(".jsonl", "_evaluated.jsonl")
        eval_files = glob.glob(os.path.join(eval_base_dir, "run_1", eval_pattern))

        status_lookup = {}
        if eval_files:
            for ef in eval_files:
                with open(ef, "r", encoding="utf-8") as f:
                    for line in f:
                        try:
                            d = json.loads(line)
                            status_lookup[str(d.get("task_num", ""))] = d.get("status", "Unknown")
                        except Exception:
                            continue
        else:
            logger.warning(f"No eval files for {friendly_name} — status will be Unknown")

        loaded = 0
        for pred_file in pred_files:
            with open(pred_file, "r", encoding="utf-8") as f:
                for line in f:
                    try:
                        d = json.loads(line)
                        tid = str(d.get("task_num", d.get("task_id", "")))
                        if not tid:
                            continue

                        conds_obj = d.get("conditions", {})
                        if not conds_obj:
                            continue

                        focal = d.get("python_solution", d.get("code", ""))
                        doc   = d.get("description", d.get("docstring", "No description."))
                        status = status_lookup.get(tid, "Unknown")

                        entries = []
                        for line_num, cond_val in conds_obj.items():
                            if isinstance(cond_val, dict):
                                ctext = cond_val.get("condition_text", "")
                            else:
                                ctext = str(cond_val)
                            if not ctext or not ctext.strip():
                                continue
                            entries.append({
                                "condition_text": ctext.strip(),
                                "target_line":    line_num,
                                "eval_status":    status,
                                "focal_code":     focal,
                                "docstring":      doc,
                            })

                        if not entries:
                            continue

                        if tid not in conditions_data:
                            conditions_data[tid] = {}
                        conditions_data[tid][friendly_name] = entries
                        loaded += 1

                    except Exception:
                        continue

        logger.info(f"{friendly_name}: loaded conditions for {loaded} tasks")

    logger.info(f"Total tasks with conditions: {len(conditions_data)}")
    return conditions_data


def score_all_plans(conditions_data, output_file, max_workers=5):
    """Score every (task, model, target_line) condition triple in parallel.

    Uses MD5-based caching (stable_hash) to avoid rescoring. Writes JSONL:
      {task_id, model, target_line, completeness, correctness, reasoning,
       eval_status, condition_text, focal_code}
    """
    # Load cache from existing output file
    cache = {}
    if os.path.exists(output_file):
        with open(output_file, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    r = json.loads(line)
                    key = stable_hash(r["condition_text"] + r["model"] + str(r["target_line"]))
                    cache[key] = r
                except Exception:
                    continue
        logger.info(f"Plan quality cache: {len(cache)} existing scores loaded")

    # Build job list
    jobs = []
    for tid, models in conditions_data.items():
        for model_name, entries in models.items():
            for entry in entries:
                key = stable_hash(entry["condition_text"] + model_name + str(entry["target_line"]))
                if key not in cache:
                    jobs.append({
                        "task_id":        tid,
                        "model":          model_name,
                        "cache_key":      key,
                        **entry,
                    })

    logger.info(f"Plan quality: {len(cache)} cached, {len(jobs)} new to score")

    writer = ThreadSafeWriter(output_file)

    def score_one(job):
        tl_content = _extract_target_line_content(job["focal_code"], job["target_line"])
        result = call_plan_judge(
            condition_text=job["condition_text"],
            focal_code=job["focal_code"],
            target_line=job["target_line"],
            target_line_content=tl_content,
        )
        if result is None:
            return None
        record = {
            "task_id":        job["task_id"],
            "model":          job["model"],
            "target_line":    job["target_line"],
            "completeness":   result["completeness"],
            "correctness":    result["correctness"],
            "reasoning":      result.get("reasoning", ""),
            "eval_status":    job["eval_status"],
            "condition_text": job["condition_text"],
            "focal_code":     job["focal_code"],
        }
        writer.write(record)
        return (job["cache_key"], record)

    if jobs:
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {executor.submit(score_one, job): job for job in jobs}
            for future in tqdm(as_completed(futures), total=len(jobs), desc="Scoring plans"):
                res = future.result()
                if res:
                    cache[res[0]] = res[1]

    logger.info(f"Plan quality scoring complete. Total scored: {len(cache)}")
    return list(cache.values())


def _cochran_n(population_size, z=1.96, p=0.5, e=0.18):
    # e=0.18 → ~30 items at 95% CI (fits 30-60 min for 3 annotators at ~1 min/item)
    n0 = (z ** 2 * p * (1 - p)) / (e ** 2)
    return math.ceil(n0 / (1 + (n0 - 1) / population_size))


def build_error_taxonomy(plan_scores):
    """Cross-tabulate plan quality tier × eval status per model.

    Aggregates across target lines per (task_id, model) pair first.
    4 buckets per arXiv:2507.06980:
      High plan + Pass  → Success
      High plan + Fail  → Coding Bottleneck
      Low plan  + Pass  → Shortcut/Memorisation
      Low plan  + Fail  → Reasoning Bottleneck
    Medium plan tasks go into a Medium bucket (not classified into the 4).

    Returns dict: {model: {bucket: count, "total": int}}
    """
    import math as _math

    if not plan_scores:
        return {}

    df = pd.DataFrame(plan_scores)
    df["avg_score"] = (df["completeness"] + df["correctness"]) / 2.0

    def tier(avg):
        if avg >= 3.5: return "High"
        if avg >= 2.5: return "Medium"
        return "Low"

    # Aggregate per (task_id, model): average across all target lines
    agg = (
        df.groupby(["task_id", "model"])
        .agg(avg_score=("avg_score", "mean"), eval_status=("eval_status", "first"))
        .reset_index()
    )
    agg["tier"] = agg["avg_score"].apply(tier)
    agg["passed"] = agg["eval_status"].str.upper() == "PASS"

    taxonomy = {}
    for model, grp in agg.groupby("model"):
        buckets = {
            "Success":              int(((grp["tier"] == "High")   & grp["passed"]).sum()),
            "Coding_Bottleneck":    int(((grp["tier"] == "High")   & ~grp["passed"]).sum()),
            "Shortcut_Memorisation":int(((grp["tier"] == "Low")    & grp["passed"]).sum()),
            "Reasoning_Bottleneck": int(((grp["tier"] == "Low")    & ~grp["passed"]).sum()),
            "Medium_Plan_Pass":     int(((grp["tier"] == "Medium") & grp["passed"]).sum()),
            "Medium_Plan_Fail":     int(((grp["tier"] == "Medium") & ~grp["passed"]).sum()),
            "total":                len(grp),
        }
        taxonomy[model] = buckets

    return taxonomy


def export_human_validation_sample(plan_scores, output_dir, seed=42):
    """Export a Cochran-sized stratified sample for three-annotator human validation.

    Prepends 3 anchor rows (IS_ANCHOR=True) that all annotators must review first.
    Cochran: N=total plans, z=1.96, p=0.5, e=0.18 → ~30 items (30-60 min per annotator).
    Stratified by model × quality tier to ensure coverage across all models and tiers.

    Columns written:
      task_id, model, target_line, focal_code, condition_text, eval_status,
      llm_completeness, llm_correctness, llm_reasoning, IS_ANCHOR,
      annotator1_completeness, annotator1_correctness,
      annotator2_completeness, annotator2_correctness,
      annotator3_completeness, annotator3_correctness, notes
    """
    import random as _random
    _random.seed(seed)

    if not plan_scores:
        logger.warning("No plan scores to sample from — skipping human validation export")
        return

    df = pd.DataFrame(plan_scores)
    df["avg_score"] = (df["completeness"] + df["correctness"]) / 2.0

    def tier(avg):
        if avg >= 3.5: return "High"
        if avg >= 2.5: return "Medium"
        return "Low"

    df["tier"] = df["avg_score"].apply(tier)

    N = len(df)
    n_cochran = _cochran_n(N)
    logger.info(f"Human validation: N={N} total plans, Cochran n={n_cochran} (95% CI, e=0.18, ~30-60 min per annotator)")

    # Stratified sample: proportional by (model × tier)
    sampled = []
    strata = df.groupby(["model", "tier"])
    for (model, t), grp in strata:
        prop = len(grp) / N
        n_from_stratum = max(1, round(n_cochran * prop))
        take = min(n_from_stratum, len(grp))
        sampled.append(grp.sample(n=take, random_state=seed))

    sample_df = pd.concat(sampled).sample(frac=1, random_state=seed).head(n_cochran)

    # Anchor rows — real examples from predictions_realworld_1 used as calibration.
    # All 3 annotators must score these before the main sample; scores are pre-filled
    # as the ground truth so annotators can check their calibration.
    _high_focal = (
        "class Solution:\n"
        "    WEEKDAYS = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']\n\n"
        "    def get_weekday_index(self, weekday: str) -> int:\n"
        "        try:\n"
        "            return self.WEEKDAYS.index(weekday.lower())\n"
        "        except ValueError:\n"
        "            raise ValueError(f\"Invalid weekday name {weekday!r}\") from None"
    )
    _high_cond = (
        "To execute line 7 `raise ValueError(...)`, the try block must raise a ValueError at "
        "`WEEKDAYS.index(weekday.lower())`. This happens when `weekday.lower()` is not present "
        "in WEEKDAYS. The input must be a string (so .lower() succeeds) but not a valid weekday "
        "name, e.g. weekday='invalidday'."
    )
    _med_focal = (
        "class Solution:\n"
        "    def get_encoder(self):\n"
        "        # Get the global encoder object. Returns: Encoder\n"
        "        return global_encoder"
    )
    _med_cond = (
        "To execute line 4 `return global_encoder`, the function get_encoder must reach its "
        "termination point without encountering any further statements. All preceding lines (1-3) "
        "must execute successfully and no exceptions or errors are raised. The variable "
        "global_encoder must be defined and accessible within the scope of the Solution class."
    )
    _low_focal = (
        "class Solution:\n"
        "    def set_encoder(self, encoder):\n"
        "        # Set the global encoder object.\n"
        "        global global_encoder\n"
        "        global_encoder = encoder"
    )
    _low_cond = (
        "For line 1 `from __future__ import annotations` to be executed, the script must be run "
        "in an environment where Python's from __future__ import annotations can be processed. "
        "This typically requires the interpreter to be invoked with -X futures or by importing "
        "the module in a way that activates the future."
    )
    anchors = pd.DataFrame([
        {
            "task_id": "ANCHOR_1", "model": "ANCHOR", "target_line": "7",
            "focal_code": _high_focal, "condition_text": _high_cond, "eval_status": "Pass",
            "llm_completeness": 5, "llm_correctness": 5,
            "llm_reasoning": "Completeness 5: identifies all constraints (must be str, not in WEEKDAYS, except branch triggered). Correctness 5: matches the actual branch condition exactly.",
            "IS_ANCHOR": True,
            "annotator1_completeness": 5, "annotator1_correctness": 5,
            "annotator2_completeness": 5, "annotator2_correctness": 5,
            "annotator3_completeness": 5, "annotator3_correctness": 5, "notes": "HIGH quality anchor",
        },
        {
            "task_id": "ANCHOR_2", "model": "ANCHOR", "target_line": "4",
            "focal_code": _med_focal, "condition_text": _med_cond, "eval_status": "Fail",
            "llm_completeness": 3, "llm_correctness": 3,
            "llm_reasoning": "Completeness 3: identifies global_encoder must exist but misses there are no branches; fails to mention set_encoder() must be called first. Correctness 3: not wrong but vacuously describes an unconditional path as if it has prerequisites.",
            "IS_ANCHOR": True,
            "annotator1_completeness": 3, "annotator1_correctness": 3,
            "annotator2_completeness": 3, "annotator2_correctness": 3,
            "annotator3_completeness": 3, "annotator3_correctness": 3, "notes": "MEDIUM quality anchor",
        },
        {
            "task_id": "ANCHOR_3", "model": "ANCHOR", "target_line": "1",
            "focal_code": _low_focal, "condition_text": _low_cond, "eval_status": "Fail",
            "llm_completeness": 1, "llm_correctness": 1,
            "llm_reasoning": "Completeness 1: entirely misses the target — line 1 is a module-level import always executed; model should say 'call set_encoder() with any Encoder instance'. Correctness 1: factually wrong — from __future__ import annotations is valid Python 3.7+ with no special flags.",
            "IS_ANCHOR": True,
            "annotator1_completeness": 1, "annotator1_correctness": 1,
            "annotator2_completeness": 1, "annotator2_correctness": 1,
            "annotator3_completeness": 1, "annotator3_correctness": 1, "notes": "LOW quality anchor",
        },
    ])

    # Add empty fill columns to main sample
    for col in ["IS_ANCHOR", "annotator1_completeness", "annotator1_correctness",
                "annotator2_completeness", "annotator2_correctness",
                "annotator3_completeness", "annotator3_correctness", "notes"]:
        if col not in sample_df.columns:
            sample_df[col] = ""
    sample_df["IS_ANCHOR"] = False

    output_cols = [
        "task_id", "model", "target_line", "focal_code", "condition_text", "eval_status",
        "llm_completeness", "llm_correctness", "llm_reasoning", "IS_ANCHOR",
        "annotator1_completeness", "annotator1_correctness",
        "annotator2_completeness", "annotator2_correctness",
        "annotator3_completeness", "annotator3_correctness", "notes",
    ]

    final = pd.concat([anchors[output_cols], sample_df[output_cols]], ignore_index=True)
    out_path = os.path.join(output_dir, "plan_quality_human_validation.csv")
    final.to_csv(out_path, index=False)
    logger.info(f"Saved human validation CSV: {out_path} ({len(sample_df)} sample + 3 anchors)")


def compute_human_agreement(human_validated_csv, output_dir):
    """Compute inter-rater agreement after all three annotators fill the CSV.

    Metrics (per Zheng et al. 2023 / Krippendorff 2011):
      - Inter-human Cohen's Kappa (weighted), averaged over all 3 annotator pairs
      - LLM-human Spearman rho (LLM scores vs average human scores across 3 annotators)
      - Krippendorff's alpha across all 4 raters (LLM + 3 humans)

    Acceptable thresholds (Zheng et al. 2023): human-LLM rho >= 0.60; inter-human Kappa >= 0.60
    """
    try:
        from scipy.stats import spearmanr
        from sklearn.metrics import cohen_kappa_score
    except ImportError:
        logger.error("scipy and scikit-learn required for agreement computation")
        return

    df = pd.read_csv(human_validated_csv)
    # Skip anchor rows
    df = df[df["IS_ANCHOR"] != True].copy()

    required = ["llm_completeness", "llm_correctness",
                "annotator1_completeness", "annotator1_correctness",
                "annotator2_completeness", "annotator2_correctness",
                "annotator3_completeness", "annotator3_correctness"]
    missing = [c for c in required if c not in df.columns or df[c].isna().all()]
    if missing:
        logger.error(f"Human validation CSV missing filled columns: {missing}")
        return

    df = df.dropna(subset=required)
    if len(df) < 10:
        logger.error("Fewer than 10 annotated rows — cannot compute reliable agreement")
        return

    results = {}
    for dim in ["completeness", "correctness"]:
        llm  = df[f"llm_{dim}"].astype(int).values
        ann1 = df[f"annotator1_{dim}"].astype(int).values
        ann2 = df[f"annotator2_{dim}"].astype(int).values
        ann3 = df[f"annotator3_{dim}"].astype(int).values
        avg_human = (ann1 + ann2 + ann3) / 3.0

        rho_llm_human, p_rho = spearmanr(llm, avg_human)
        # Average pairwise weighted kappa across all 3 annotator pairs
        k12 = cohen_kappa_score(ann1, ann2, weights="quadratic")
        k13 = cohen_kappa_score(ann1, ann3, weights="quadratic")
        k23 = cohen_kappa_score(ann2, ann3, weights="quadratic")
        kappa_inter = (k12 + k13 + k23) / 3.0

        # Krippendorff's alpha (ordinal) across all 4 raters (LLM + 3 humans)
        def krippendorff_alpha_ordinal(ratings_matrix):
            n_raters, n_items = ratings_matrix.shape
            Do = 0.0
            De = 0.0
            for i in range(n_items):
                col = ratings_matrix[:, i]
                pairs = [(col[r1], col[r2]) for r1 in range(n_raters) for r2 in range(r1+1, n_raters)]
                Do += sum((a - b) ** 2 for a, b in pairs)
            all_vals = ratings_matrix.flatten()
            n_total = len(all_vals)
            for v1 in all_vals:
                for v2 in all_vals:
                    De += (v1 - v2) ** 2
            Do /= n_items
            De /= (n_total - 1)
            return 1 - (Do / De) if De > 0 else 1.0

        ratings = np.array([llm, ann1, ann2, ann3])
        alpha = krippendorff_alpha_ordinal(ratings)

        results[dim] = {
            "llm_human_spearman_rho": round(float(rho_llm_human), 3),
            "llm_human_spearman_p":   round(float(p_rho), 4),
            "inter_human_kappa_weighted": round(float(kappa_inter), 3),
            "krippendorff_alpha_ordinal": round(float(alpha), 3),
            "n_annotated": len(df),
            "threshold_acceptable": rho_llm_human >= 0.60 and kappa_inter >= 0.60,
        }
        logger.info(
            f"[{dim.upper()}] Spearman rho (LLM vs human avg): {rho_llm_human:.3f} (p={p_rho:.4f}) | "
            f"Inter-human Kappa: {kappa_inter:.3f} | Krippendorff alpha: {alpha:.3f}"
        )
        status = "ACCEPTABLE" if results[dim]["threshold_acceptable"] else "BELOW THRESHOLD"
        logger.info(f"  => Agreement: {status} (threshold: rho>=0.60, kappa>=0.60)")

    out_path = os.path.join(output_dir, "plan_quality_human_agreement.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    logger.info(f"Saved inter-rater agreement: {out_path}")


def select_evaluation_groups():
    """Returns Dict of {group_name: [(pattern, config_name), ...]}"""
    return {
        "best_configs": [
            ("pynguin_results.jsonl", "Pynguin (Baseline)"),
            ("linecov2_Qwen3-4B-Instruct*_temp_1.0.jsonl", "Qwen3-4B-Instruct Two-Shot CoT T=1.0"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_0.0.jsonl", "Ministral-3-8B-Instruct Two-Shot CoT T=0.0"),
            ("linecov2_granite-4.0-micro_temp_0.2.jsonl", "granite-4.0-micro Two-Shot CoT T=0.2"),
            ("linecov_Ministral-3-3B-Reasoning*_temp_0.8.jsonl", "Ministral-3-3B-Reasoning One-Shot T=0.8"),
            ("linecov_gemma-3-4b-it_temp_0.2.jsonl", "gemma-3-4b-it One-Shot T=0.2"),
        ],
        "temperature_ablation": [
            ("linecov2_Qwen3-4B-Instruct*_temp_0.0.jsonl", "Qwen3-4B-Instruct Two-Shot CoT T=0.0"),
            ("linecov2_Qwen3-4B-Instruct*_temp_0.8.jsonl", "Qwen3-4B-Instruct Two-Shot CoT T=0.8"),
            ("linecov2_Qwen3-4B-Instruct*_temp_1.0.jsonl", "Qwen3-4B-Instruct Two-Shot CoT T=1.0"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_0.0.jsonl", "Ministral-3-8B-Instruct Two-Shot CoT T=0.0"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_0.8.jsonl", "Ministral-3-8B-Instruct Two-Shot CoT T=0.8"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_1.0.jsonl", "Ministral-3-8B-Instruct Two-Shot CoT T=1.0"),
        ],
        "prompting_ablation": [
            ("linecov_Qwen3-4B-Instruct*_temp_1.0.jsonl", "Qwen3-4B-Instruct One-Shot T=1.0"),
            ("linecov2_Qwen3-4B-Instruct*_temp_1.0.jsonl", "Qwen3-4B-Instruct Two-Shot CoT T=1.0"),
            ("linecov_Ministral-3-8B-Instruct*_temp_0.0.jsonl", "Ministral-3-8B-Instruct One-Shot T=0.0"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_0.0.jsonl", "Ministral-3-8B-Instruct Two-Shot CoT T=0.0"),
        ],
        # All 5 architectures × 3 temps × 2 prompts + 1 baseline = 31 configs
        "full_factorial": [
            # Dense 4B (Qwen3)
            ("linecov_Qwen3-4B-Instruct*_temp_0.0.jsonl", "Qwen3-4B-Instruct One-Shot T=0.0"),
            ("linecov_Qwen3-4B-Instruct*_temp_0.8.jsonl", "Qwen3-4B-Instruct One-Shot T=0.8"),
            ("linecov_Qwen3-4B-Instruct*_temp_1.0.jsonl", "Qwen3-4B-Instruct One-Shot T=1.0"),
            ("linecov2_Qwen3-4B-Instruct*_temp_0.0.jsonl", "Qwen3-4B-Instruct Two-Shot T=0.0"),
            ("linecov2_Qwen3-4B-Instruct*_temp_0.8.jsonl", "Qwen3-4B-Instruct Two-Shot T=0.8"),
            ("linecov2_Qwen3-4B-Instruct*_temp_1.0.jsonl", "Qwen3-4B-Instruct Two-Shot T=1.0"),

            # Quantized 8B (Ministral-8B AWQ)
            ("linecov_Ministral-3-8B-Instruct*_temp_0.0.jsonl", "Ministral-3-8B-Instruct One-Shot T=0.0"),
            ("linecov_Ministral-3-8B-Instruct*_temp_0.8.jsonl", "Ministral-3-8B-Instruct One-Shot T=0.8"),
            ("linecov_Ministral-3-8B-Instruct*_temp_1.0.jsonl", "Ministral-3-8B-Instruct One-Shot T=1.0"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_0.0.jsonl", "Ministral-3-8B-Instruct Two-Shot T=0.0"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_0.8.jsonl", "Ministral-3-8B-Instruct Two-Shot T=0.8"),
            ("linecov2_Ministral-3-8B-Instruct*_temp_1.0.jsonl", "Ministral-3-8B-Instruct Two-Shot T=1.0"),

            # Mamba Hybrid (granite)
            ("linecov_granite-4.0-micro_temp_0.0.jsonl", "granite-4.0-micro One-Shot T=0.0"),
            ("linecov_granite-4.0-micro_temp_0.8.jsonl", "granite-4.0-micro One-Shot T=0.8"),
            ("linecov_granite-4.0-micro_temp_1.0.jsonl", "granite-4.0-micro One-Shot T=1.0"),
            ("linecov2_granite-4.0-micro_temp_0.0.jsonl", "granite-4.0-micro Two-Shot T=0.0"),
            ("linecov2_granite-4.0-micro_temp_0.8.jsonl", "granite-4.0-micro Two-Shot T=0.8"),
            ("linecov2_granite-4.0-micro_temp_1.0.jsonl", "granite-4.0-micro Two-Shot T=1.0"),

            # Reasoning (Ministral-3B with Internal CoT)
            ("linecov_Ministral-3-3B-Reasoning*_temp_0.0.jsonl", "Ministral-3-3B-Reasoning One-Shot T=0.0"),
            ("linecov_Ministral-3-3B-Reasoning*_temp_0.8.jsonl", "Ministral-3-3B-Reasoning One-Shot T=0.8"),
            ("linecov_Ministral-3-3B-Reasoning*_temp_1.0.jsonl", "Ministral-3-3B-Reasoning One-Shot T=1.0"),
            ("linecov2_Ministral-3-3B-Reasoning*_temp_0.0.jsonl", "Ministral-3-3B-Reasoning Two-Shot T=0.0"),
            ("linecov2_Ministral-3-3B-Reasoning*_temp_0.8.jsonl", "Ministral-3-3B-Reasoning Two-Shot T=0.8"),
            ("linecov2_Ministral-3-3B-Reasoning*_temp_1.0.jsonl", "Ministral-3-3B-Reasoning Two-Shot T=1.0"),

            # Dense 4B (gemma)
            ("linecov_gemma-3-4b-it_temp_0.0.jsonl", "gemma-3-4b-it One-Shot T=0.0"),
            ("linecov_gemma-3-4b-it_temp_0.8.jsonl", "gemma-3-4b-it One-Shot T=0.8"),
            ("linecov_gemma-3-4b-it_temp_1.0.jsonl", "gemma-3-4b-it One-Shot T=1.0"),
            ("linecov2_gemma-3-4b-it_temp_0.0.jsonl", "gemma-3-4b-it Two-Shot T=0.0"),
            ("linecov2_gemma-3-4b-it_temp_0.8.jsonl", "gemma-3-4b-it Two-Shot T=0.8"),
            ("linecov2_gemma-3-4b-it_temp_1.0.jsonl", "gemma-3-4b-it Two-Shot T=1.0"),

            # Baseline
            ("pynguin_results.jsonl", "Pynguin (Baseline)"),
        ],
        # Second experiment: 5 models × 2 modes × 3 tiers (T=0.0 only).
        # Predictions expected in base_dir/run_1/tier_A|B|C/*.jsonl
        # Pass --eval_dir evaluation_results/second_experiment when running.
        "second_experiment_tier_A": [
            ("tier_A/linecov_gemma-4-E4B-it_temp_0.0.jsonl",            "gemma-4-E4B-it One-Step Tier-A"),
            ("tier_A/linecov2_gemma-4-E4B-it_temp_0.0.jsonl",           "gemma-4-E4B-it Two-Step Tier-A"),
            ("tier_A/linecov_granite-4.0-micro_temp_0.0.jsonl",          "granite-4.0-micro One-Step Tier-A"),
            ("tier_A/linecov2_granite-4.0-micro_temp_0.0.jsonl",         "granite-4.0-micro Two-Step Tier-A"),
            ("tier_A/linecov_Ministral-3-3B-Reasoning-2512_temp_0.0.jsonl",  "Ministral-3-3B-Reasoning One-Step Tier-A"),
            ("tier_A/linecov2_Ministral-3-3B-Reasoning-2512_temp_0.0.jsonl", "Ministral-3-3B-Reasoning Two-Step Tier-A"),
            ("tier_A/linecov_Qwen3-4B-Thinking-2507_temp_0.0.jsonl",    "Qwen3-4B-Thinking One-Step Tier-A"),
            ("tier_A/linecov2_Qwen3-4B-Thinking-2507_temp_0.0.jsonl",   "Qwen3-4B-Thinking Two-Step Tier-A"),
            ("tier_A/linecov_Qwen3.5-4B_temp_0.0.jsonl",                "Qwen3.5-4B One-Step Tier-A"),
            ("tier_A/linecov2_Qwen3.5-4B_temp_0.0.jsonl",               "Qwen3.5-4B Two-Step Tier-A"),
        ],
        "second_experiment_tier_B": [
            ("tier_B/linecov_gemma-4-E4B-it_temp_0.0.jsonl",            "gemma-4-E4B-it One-Step Tier-B"),
            ("tier_B/linecov2_gemma-4-E4B-it_temp_0.0.jsonl",           "gemma-4-E4B-it Two-Step Tier-B"),
            ("tier_B/linecov_granite-4.0-micro_temp_0.0.jsonl",          "granite-4.0-micro One-Step Tier-B"),
            ("tier_B/linecov2_granite-4.0-micro_temp_0.0.jsonl",         "granite-4.0-micro Two-Step Tier-B"),
            ("tier_B/linecov_Ministral-3-3B-Reasoning-2512_temp_0.0.jsonl",  "Ministral-3-3B-Reasoning One-Step Tier-B"),
            ("tier_B/linecov2_Ministral-3-3B-Reasoning-2512_temp_0.0.jsonl", "Ministral-3-3B-Reasoning Two-Step Tier-B"),
            ("tier_B/linecov_Qwen3-4B-Thinking-2507_temp_0.0.jsonl",    "Qwen3-4B-Thinking One-Step Tier-B"),
            ("tier_B/linecov2_Qwen3-4B-Thinking-2507_temp_0.0.jsonl",   "Qwen3-4B-Thinking Two-Step Tier-B"),
            ("tier_B/linecov_Qwen3.5-4B_temp_0.0.jsonl",                "Qwen3.5-4B One-Step Tier-B"),
            ("tier_B/linecov2_Qwen3.5-4B_temp_0.0.jsonl",               "Qwen3.5-4B Two-Step Tier-B"),
        ],
        "second_experiment_tier_C": [
            ("tier_C/linecov_gemma-4-E4B-it_temp_0.0.jsonl",            "gemma-4-E4B-it One-Step Tier-C"),
            ("tier_C/linecov2_gemma-4-E4B-it_temp_0.0.jsonl",           "gemma-4-E4B-it Two-Step Tier-C"),
            ("tier_C/linecov_granite-4.0-micro_temp_0.0.jsonl",          "granite-4.0-micro One-Step Tier-C"),
            ("tier_C/linecov2_granite-4.0-micro_temp_0.0.jsonl",         "granite-4.0-micro Two-Step Tier-C"),
            ("tier_C/linecov_Ministral-3-3B-Reasoning-2512_temp_0.0.jsonl",  "Ministral-3-3B-Reasoning One-Step Tier-C"),
            ("tier_C/linecov2_Ministral-3-3B-Reasoning-2512_temp_0.0.jsonl", "Ministral-3-3B-Reasoning Two-Step Tier-C"),
            ("tier_C/linecov_Qwen3-4B-Thinking-2507_temp_0.0.jsonl",    "Qwen3-4B-Thinking One-Step Tier-C"),
            ("tier_C/linecov2_Qwen3-4B-Thinking-2507_temp_0.0.jsonl",   "Qwen3-4B-Thinking Two-Step Tier-C"),
            ("tier_C/linecov_Qwen3.5-4B_temp_0.0.jsonl",                "Qwen3.5-4B One-Step Tier-C"),
            ("tier_C/linecov2_Qwen3.5-4B_temp_0.0.jsonl",               "Qwen3.5-4B Two-Step Tier-C"),
        ],
    }

def load_data(base_dir, evaluation_group="best_configs", eval_dir=None):
    """Load predictions and join with evaluation results, returning only status=Pass tests.

    Two-stage loading:
    1. Predictions from base_dir/run_1/*.jsonl (test code)
    2. Evaluation results from eval_dir/run_1/*_evaluated.jsonl (status)

    Returns (tasks, focal_methods, docstrings, pass_rate_stats).
    """
    groups = select_evaluation_groups()
    if evaluation_group not in groups:
        raise ValueError(f"Unknown group: {evaluation_group}")

    selected_models = groups[evaluation_group]
    tasks = {}
    focal_methods = {}
    docstrings = {}
    pass_rate_stats = {}

    logger.info(f"Loading data for group: {evaluation_group}...")
    logger.info(f"Eval dir override: {eval_dir if eval_dir else '(none - using heuristic)'}")

    if eval_dir:
        eval_base_dir = eval_dir
    elif "predictions" in base_dir.lower():
        # Heuristic: Remove any TestEval/ prefix and replace predictions with evaluation_results
        base_cleaned = base_dir.split(os.sep)[-1] if os.sep in base_dir else base_dir
        if "predictions_realworld" in base_cleaned:
            eval_base_dir = "evaluation_results_realworld"
        elif "predictions_initial" in base_cleaned:
            eval_base_dir = "evaluation_results_initial"
        else:
            eval_base_dir = base_dir.replace("predictions", "evaluation_results")
    else:
        eval_base_dir = base_dir

    for pattern, friendly_name in selected_models:
        pred_search_path = os.path.join(base_dir, "run_1", pattern)
        pred_files = glob.glob(pred_search_path)

        eval_pattern = pattern.replace('.jsonl', '_evaluated.jsonl')
        eval_search_path = os.path.join(eval_base_dir, "run_1", eval_pattern)
        eval_files = glob.glob(eval_search_path)

        if not pred_files:
            logger.warning(f"No prediction files found for {friendly_name}: {pred_search_path}")
            continue

        if not eval_files:
            logger.warning(f"No evaluation files found for {friendly_name}: {eval_search_path}")
            logger.warning(f"Skipping Pass filter for this model (will load all tests)")
            # Fall back to loading without status filter
            eval_files = None

        status_lookup = {}
        if eval_files:
            for eval_filepath in eval_files:
                with open(eval_filepath, 'r', encoding='utf-8') as f:
                    for line in f:
                        try:
                            d = json.loads(line)
                            task_num = str(d.get('task_num', ''))
                            status_lookup[task_num] = d.get('status', 'Unknown')
                        except Exception:
                            continue

        pass_count = 0
        total_count = 0

        for pred_filepath in pred_files:
            with open(pred_filepath, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        d = json.loads(line)
                        total_count += 1

                        tid = str(d.get('task_num', d.get('task_id', '')))
                        if not tid: continue

                        # Filter by Pass status (if evaluation results available)
                        if status_lookup:
                            status = status_lookup.get(tid, 'Unknown')
                            if status != "Pass":
                                continue

                        pass_count += 1

                        # Extract test code
                        tests_obj = d.get('tests', {})
                        test_code = ""
                        if isinstance(tests_obj, dict):
                            for k, v in tests_obj.items():
                                if isinstance(v, dict):
                                    test_code = v.get('test_code', '')
                                else:
                                    test_code = v
                                break

                        if not test_code or not test_code.strip(): continue

                        if tid not in tasks: tasks[tid] = {}
                        tasks[tid][friendly_name] = test_code

                        if tid not in focal_methods:
                            focal_methods[tid] = d.get('code') or d.get('python_solution', '')

                        if tid not in docstrings:
                            docstrings[tid] = (d.get('prompt') or d.get('docstring') or "No docstring.")

                    except Exception:
                        continue

        # Record pass rate statistics
        pass_rate = (pass_count / total_count * 100) if total_count > 0 else 0
        pass_rate_stats[friendly_name] = {
            'pass_count': pass_count,
            'total_count': total_count,
            'pass_rate': pass_rate
        }
        logger.info(f"{friendly_name}: {pass_count}/{total_count} passing ({pass_rate:.1f}%)")

    logger.info(f"Loaded {len(tasks)} tasks with passing tests across all models.")
    return tasks, focal_methods, docstrings, pass_rate_stats

# Sampling strategy
def perform_stratified_sampling(df, output_dir, group_name, n_per_stratum=10, seed=42):
    """Samples from Ties, Marginal Wins, and Clear Wins for human validation."""
    valid = df[df['bias_status'] == 'None'].copy()
    if valid.empty: return

    def classify_diff(row):
        d = row['score_diff']
        if d <= TIE_THRESHOLD: return 'Tie'  # <= 2.0 for 1-5 scale
        if d <= 8.0: return 'Marginal'  # Adjusted for 1-5 scale (was 4.0 for 0-2 scale)
        return 'Clear'
    
    valid['stratum'] = valid.apply(classify_diff, axis=1)
    sampled_rows = []
    
    logger.info(f"Sampling for human validation ({group_name})...")
    for stratum in ['Tie', 'Marginal', 'Clear']:
        subset = valid[valid['stratum'] == stratum]
        count = min(len(subset), n_per_stratum)
        if count > 0:
            sampled_rows.append(subset.sample(n=count, random_state=seed))

    if sampled_rows:
        final_sample = pd.concat(sampled_rows).sample(frac=1, random_state=seed)
        path = os.path.join(output_dir, f"stratified_human_eval_{group_name}.csv")
        cols = ['task_id', 'stratum', 'score_diff', 'model_a', 'model_b',
                'model_a_total_score', 'model_b_total_score',
                'docstring', 'focal_code', 'code_a', 'code_b', 'reasoning_pass_full']
        final_sample[cols].to_csv(path, index=False)
        logger.info(f"Saved human sample to {path}")

def load_global_comparison_cache(output_dir):
    """Load all previously completed comparisons from ALL group files for deduplication."""
    cache = {}  # key: comparison_key -> value: decision result

    # Search for all pairwise_judgements_*.jsonl files in output directory
    cache_files = glob.glob(os.path.join(output_dir, "pairwise_judgements_*.jsonl"))

    for cache_file in cache_files:
        with open(cache_file, 'r') as f:
            for line in f:
                try:
                    result = json.loads(line)
                    # Create unique key based on task_id, model names, AND the actual code being compared
                    # This ensures we can reuse comparisons across groups if they compare the same code
                    # Use stable_hash instead of hash() for persistence across Python sessions
                    code_hash = stable_hash(result['code_a'] + result['code_b'])
                    comparison_key = f"{result['task_id']}||{result['model_a']}||{result['model_b']}||{code_hash}"
                    cache[comparison_key] = result
                except:
                    continue

    logger.info(f"Loaded {len(cache)} comparisons from global cache across all groups")
    return cache

def main():
    parser = argparse.ArgumentParser(description="LLM-as-Judge Evaluation System")
    parser.add_argument("--predictions_dir", type=str, default="TestEval/predictions_realworld")
    parser.add_argument("--eval_dir", type=str, default=None,
                        help="Path to evaluation results directory (e.g. evaluation_results_realworld_1). "
                             "Overrides auto-detection. Required for correct Pass-status filtering.")
    parser.add_argument("--output_dir", type=str, default="TestEval/predictions_judgellm")
    parser.add_argument("--evaluation_group", type=str, default="best_configs",
                        choices=["best_configs", "temperature_ablation", "prompting_ablation", "full_factorial",
                                 "second_experiment_tier_A", "second_experiment_tier_B", "second_experiment_tier_C",
                                 "second_experiment_all", "all"])
    parser.add_argument("--human_sample_size", type=int, default=10)
    parser.add_argument("--task_sample_size", type=int, default=None, help="Pilot study: sample N tasks")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--use_cache", action="store_true", default=True,
                        help="Reuse comparisons from other groups (default: True)")
    parser.add_argument("--no_cache", action="store_true",
                        help="Disable cache and re-evaluate all comparisons")
    parser.add_argument("--max_workers", type=int, default=5,
                        help="Max parallel API requests (default: 5). Anthropic handles concurrency well.")
    # Plan quality mode (Step 6 — Jiang et al. 2023 / G-Eval / arXiv:2507.06980)
    parser.add_argument("--mode", type=str, default="pairwise",
                        choices=["pairwise", "plan_quality", "both"],
                        help="pairwise=existing test code comparison; "
                             "plan_quality=score step-1 conditions (two-step CoT only); "
                             "both=run both pipelines")
    parser.add_argument("--human_agreement_csv", type=str, default=None,
                        help="Path to human-filled plan_quality_human_validation.csv "
                             "for inter-rater agreement computation (use after human annotation)")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # --- Plan quality mode (independent of pairwise pipeline) ---
    if args.mode in ("plan_quality", "both"):
        logger.info("\n" + "=" * 60)
        logger.info("PLAN QUALITY SCORING (step-1 conditions)")
        logger.info("=" * 60)

        # If human agreement CSV provided, just compute agreement and exit
        if args.human_agreement_csv:
            logger.info(f"Computing human agreement from: {args.human_agreement_csv}")
            compute_human_agreement(args.human_agreement_csv, args.output_dir)
        else:
            groups_for_plans = (
                ["best_configs", "temperature_ablation", "prompting_ablation"]
                if args.evaluation_group == "all"
                else [args.evaluation_group]
            )
            all_plan_scores = []
            for group_name in groups_for_plans:
                logger.info(f"Loading conditions for group: {group_name}")
                conditions_data = load_conditions(
                    args.predictions_dir,
                    evaluation_group=group_name,
                    eval_dir=args.eval_dir,
                )
                if not conditions_data:
                    logger.warning(f"No conditions found for group {group_name} — skipping")
                    continue

                scores_file = os.path.join(args.output_dir, f"plan_quality_scores_{group_name}.jsonl")
                scores = score_all_plans(conditions_data, scores_file, max_workers=args.max_workers)
                all_plan_scores.extend(scores)

            if all_plan_scores:
                taxonomy = build_error_taxonomy(all_plan_scores)
                tax_path = os.path.join(args.output_dir, "plan_quality_error_taxonomy.json")
                with open(tax_path, "w", encoding="utf-8") as f:
                    json.dump(taxonomy, f, indent=2)
                logger.info(f"Saved error taxonomy: {tax_path}")
                for model, buckets in taxonomy.items():
                    logger.info(f"  {model}: {buckets}")

                export_human_validation_sample(all_plan_scores, args.output_dir, seed=args.seed)
            else:
                logger.warning("No plan scores produced — check predictions_dir and eval_dir")

        if args.mode == "plan_quality":
            return  # Don't run pairwise if plan_quality-only mode

    # Load global cache once before processing any groups
    global_cache = {}
    if args.use_cache and not args.no_cache:
        logger.info("Loading global comparison cache to reuse evaluations across groups...")
        global_cache = load_global_comparison_cache(args.output_dir)
    else:
        logger.info("Cache disabled - will re-evaluate all comparisons")

    # Determine groups to run
    if args.evaluation_group == "all":
        groups_to_run = ["best_configs", "temperature_ablation", "prompting_ablation"]
    elif args.evaluation_group == "second_experiment_all":
        groups_to_run = ["second_experiment_tier_A", "second_experiment_tier_B", "second_experiment_tier_C"]
    else:
        groups_to_run = [args.evaluation_group]

    for group_name in groups_to_run:
        logger.info("\n" + "=" * 60)
        logger.info(f"STARTING EVALUATION: {group_name}")
        logger.info("=" * 60)

        # 1. Load Data (with pass rate statistics)
        tasks, focal_methods, docstrings, pass_rate_stats = load_data(args.predictions_dir, evaluation_group=group_name, eval_dir=args.eval_dir)

        # Optional: Pilot Sampling
        if args.task_sample_size and args.task_sample_size < len(tasks):
            import random
            random.seed(args.seed)
            sampled_ids = random.sample(list(tasks.keys()), args.task_sample_size)
            tasks = {tid: tasks[tid] for tid in sampled_ids}
            logger.info(f"PILOT MODE: Sampled {len(tasks)} tasks.")

        OUTPUT_FILE = os.path.join(args.output_dir, f"pairwise_judgements_{group_name}.jsonl")
        STATS_FILE = os.path.join(args.output_dir, f"evaluation_statistics_{group_name}.json")

        # Load existing results from THIS group's file for resume functionality
        local_completed = {}
        if os.path.exists(OUTPUT_FILE):
            logger.info(f"Found existing results file for {group_name}. Loading completed comparisons...")
            with open(OUTPUT_FILE, 'r') as f:
                for line in f:
                    try:
                        result = json.loads(line)
                        # Create unique key for each comparison including code hash
                        code_hash = stable_hash(result['code_a'] + result['code_b'])
                        comparison_key = f"{result['task_id']}||{result['model_a']}||{result['model_b']}||{code_hash}"
                        local_completed[comparison_key] = result
                    except:
                        continue
            logger.info(f"Loaded {len(local_completed)} completed comparisons from {group_name}.")

        # Merge global cache with local results (local takes precedence)
        available_cache = {**global_cache, **local_completed}
        logger.info(f"Total available cached comparisons: {len(available_cache)} (global: {len(global_cache)}, local: {len(local_completed)})")

        # Cost Estimation
        total_pairs = sum((len(m)*(len(m)-1))//2 for m in tasks.values() if len(m)>=2)
        total_calls = total_pairs * 2 # Double pass
        
        # Heuristic: 1 char ~= 0.25 tokens. 
        # Avg input context per call ~= Focal(300) + Doc(100) + CodeA(200) + CodeB(200) + Prompt(500) = 1300 chars
        est_input_tokens = total_calls * 1500  # Conservative estimate
        est_output_tokens = total_calls * 400  # Reasoning + JSON

        est_cost = ((est_input_tokens/1_000_000) * PRICE_INPUT_PER_M) + \
                   ((est_output_tokens/1_000_000) * PRICE_OUTPUT_PER_M)

        logger.info(f"--- COST ESTIMATION ({group_name}) ---")
        logger.info(f"Pairs: {total_pairs} | API Calls: {total_calls} (Double-Pass)")
        logger.info(f"Est. Cost: ${est_cost:.2f} (Input: ~{est_input_tokens} toks, Output: ~{est_output_tokens} toks)")
        logger.info("-------------------------------------")
        
        # Evaluation Loop with Parallel Processing
        cache_hits = 0
        new_comparisons = 0
        reused_from_other_groups = 0

        # Thread-safe writer for parallel execution
        writer = ThreadSafeWriter(OUTPUT_FILE)

        # Build list of all comparisons to perform
        comparison_jobs = []
        for task_id, models in tasks.items():
            if len(models) < 2: continue
            focal = focal_methods.get(task_id, "")
            doc = docstrings.get(task_id, "")

            # Important Selection Bias Mitigation
            # Only compare models that BOTH have passing tests for this task.
            pairs = list(itertools.combinations(models.keys(), 2))

            for m1, m2 in pairs:
                code_a = models[m1]
                code_b = models[m2]
                code_hash = stable_hash(code_a + code_b)
                comparison_key = f"{task_id}||{m1}||{m2}||{code_hash}"

                # Check if cached
                if comparison_key in available_cache:
                    cached_result = available_cache[comparison_key]
                    cache_hits += 1

                    # Write to this group's file if from another group
                    if comparison_key not in local_completed:
                        reused_from_other_groups += 1
                        writer.write(cached_result)
                    continue

                # Add to job queue for parallel processing
                comparison_jobs.append({
                    'task_id': task_id,
                    'focal': focal,
                    'doc': doc,
                    'm1': m1,
                    'code_a': code_a,
                    'm2': m2,
                    'code_b': code_b,
                    'comparison_key': comparison_key
                })

        logger.info(f"Cache hits: {cache_hits} | New comparisons to perform: {len(comparison_jobs)}")

        # Parallel execution
        if comparison_jobs:
            def evaluate_comparison(job):
                """Worker function for parallel evaluation."""
                try:
                    decision = judge_pair_double_pass(
                        job['task_id'], job['focal'], job['doc'],
                        job['m1'], job['code_a'], job['m2'], job['code_b']
                    )
                    return (job['comparison_key'], decision)
                except Exception as e:
                    logger.error(f"Failed to evaluate {job['comparison_key']}: {e}")
                    return (job['comparison_key'], None)

            # Use ThreadPoolExecutor for parallel API calls
            with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
                # Submit all jobs
                futures = {executor.submit(evaluate_comparison, job): job for job in comparison_jobs}

                # Process results as they complete
                for future in tqdm(as_completed(futures), total=len(comparison_jobs), desc=f"Evaluating {group_name}"):
                    comparison_key, decision = future.result()
                    if decision:
                        new_comparisons += 1
                        # Thread-safe write to disk
                        writer.write(decision)
                        # Add to cache to prevent duplicates
                        available_cache[comparison_key] = decision
                    else:
                        logger.warning(f"Skipping failed comparison: {comparison_key}")

        logger.info(f"Evaluation complete for {group_name}:")
        logger.info(f"  - New comparisons: {new_comparisons}")
        logger.info(f"  - Reused from other groups: {reused_from_other_groups}")
        logger.info(f"  - Already in this group: {cache_hits - reused_from_other_groups}")
        logger.info(f"  - Total skipped (cached): {cache_hits}")

        # Statistics & Sampling
        # Load ALL results from file (including previously completed ones) for complete statistics
        all_results = []
        if os.path.exists(OUTPUT_FILE):
            with open(OUTPUT_FILE, 'r') as f:
                for line in f:
                    try:
                        all_results.append(json.loads(line))
                    except:
                        continue

        if all_results:
            df = pd.DataFrame(all_results)
            
            bias_counts = df['bias_status'].value_counts().to_dict()
            winner_dist = df['final_winner_model'].value_counts().to_dict()
            
            # Win Matrix
            valid_df = df[df['bias_status'] == 'None']
            win_matrix = {}
            for _, row in valid_df.iterrows():
                w, ma, mb = row['final_winner_model'], row['model_a'], row['model_b']
                for m in [ma, mb]: win_matrix.setdefault(m, 0)
                if w == "A": win_matrix[ma] += 1
                elif w == "B": win_matrix[mb] += 1

            # TIE_THRESHOLD Sensitivity Analysis
            # Calculate tie percentage to validate threshold appropriateness
            tie_count = winner_dist.get('Tie', 0)
            tie_percentage = (tie_count / len(valid_df) * 100) if len(valid_df) > 0 else 0

            # Calculate score distribution for threshold recommendation
            score_diffs = valid_df['score_diff'].describe().to_dict()

            stats = {
                "total_comparisons": len(df),
                "bias_analysis": bias_counts,
                "winner_distribution": winner_dist,
                "win_counts": win_matrix,
                "tie_threshold_analysis": {
                    "current_threshold": TIE_THRESHOLD,
                    "tie_percentage": round(tie_percentage, 2),
                    "tie_count": tie_count,
                    "valid_comparisons": len(valid_df),
                    "score_diff_stats": {k: round(v, 2) for k, v in score_diffs.items() if k != 'count'},
                    "recommendation": (
                        "INCREASE threshold (too many ties)" if tie_percentage > 40 else
                        "DECREASE threshold (too few ties)" if tie_percentage < 10 else
                        "Threshold appears reasonable"
                    )
                },
                "est_cost_usd": est_cost,
                "pass_rate_statistics": pass_rate_stats
            }

            with open(STATS_FILE, 'w') as f: json.dump(stats, f, indent=2)

            # Log BIAS & NOISE analysis
            logger.info("\n" + "=" * 60)
            logger.info("JUDGMENT RELIABILITY ANALYSIS")
            logger.info("=" * 60)
            logger.info(f"Total Comparisons: {len(df)}")
            logger.info(f"Bias Status Breakdown:")
            for status, count in bias_counts.items():
                percentage = (count / len(df) * 100) if len(df) > 0 else 0
                logger.info(f"  - {status}: {count} ({percentage:.1f}%)")

            # Stochastic noise warning
            noise_count = bias_counts.get('Stochastic_Noise', 0)
            if noise_count > len(df) * 0.05:  # >5% noise is concerning
                logger.warning(f"⚠️  HIGH STOCHASTIC NOISE: {noise_count} comparisons ({noise_count/len(df)*100:.1f}%)")
                logger.warning(f"⚠️  Judge is inconsistent between passes (not position-dependent)")
                logger.warning(f"⚠️  Consider: lower temperature, clearer prompt, or different model")
            else:
                logger.info(f"✓ Low noise level: {noise_count} stochastic disagreements ({noise_count/len(df)*100:.1f}%)")
            logger.info("=" * 60 + "\n")

            # Log TIE_THRESHOLD analysis
            logger.info("=" * 60)
            logger.info("TIE THRESHOLD SENSITIVITY ANALYSIS")
            logger.info("=" * 60)
            logger.info(f"Current Threshold: {TIE_THRESHOLD}")
            logger.info(f"Tie Rate: {tie_percentage:.1f}% ({tie_count}/{len(valid_df)} comparisons)")
            logger.info(f"Score Diff - Median: {score_diffs.get('50%', 0):.2f}, Mean: {score_diffs.get('mean', 0):.2f}")
            threshold_rec = stats['tie_threshold_analysis']['recommendation']
            if "INCREASE" in threshold_rec:
                logger.warning(f"⚠️  {threshold_rec}")
                logger.warning(f"⚠️  Consider TIE_THRESHOLD = 3.0 or 4.0 to reduce ties")
            elif "DECREASE" in threshold_rec:
                logger.warning(f"⚠️  {threshold_rec}")
                logger.warning(f"⚠️  Consider TIE_THRESHOLD = 1.0 or 1.5 to allow more ties")
            else:
                logger.info(f"✓ {threshold_rec} (10-40% ties is acceptable)")
            logger.info("=" * 60 + "\n")

            # Log pass rate warning if significant imbalance
            logger.info("=" * 60)
            logger.info("PASS RATE ANALYSIS (Selection Bias Check)")
            logger.info("=" * 60)
            pass_counts = [s['pass_count'] for s in pass_rate_stats.values()]
            if pass_counts:
                min_pass = min(pass_counts)
                max_pass = max(pass_counts)
                if max_pass > 0 and (max_pass - min_pass) / max_pass > 0.3:
                    logger.warning(f"⚠️  SELECTION BIAS DETECTED: Pass count range {min_pass}-{max_pass}")
                    logger.warning(f"⚠️  Models with more passing tests may appear better due to larger sample size")
                    logger.warning(f"⚠️  Recommendation: Report pass rate alongside quality scores")
                else:
                    logger.info(f"✓ Pass counts well-balanced: {min_pass}-{max_pass} (acceptable range)")
            logger.info("=" * 60 + "\n")
            
            perform_stratified_sampling(
                df, args.output_dir, group_name, 
                n_per_stratum=args.human_sample_size, seed=args.seed
            )
    
    # Merge human samples if "all" was selected
    if args.evaluation_group == "all":
        logger.info("Merging human validation samples from all groups...")
        all_samples = []
        for grp in groups_to_run:
            f = os.path.join(args.output_dir, f"stratified_human_eval_{grp}.csv")
            if os.path.exists(f): all_samples.append(pd.read_csv(f))
        
        if all_samples:
            merged = pd.concat(all_samples, ignore_index=True)
            merged.to_csv(os.path.join(args.output_dir, "stratified_human_eval_ALL_GROUPS.csv"), index=False)
            logger.info("Saved merged human evaluation file.")

if __name__ == "__main__":
    main()