"""
Repatch: Re-run the 77 Pynguin comparisons where the Pynguin authorship
comment was visible to the LLM judge, breaking blind evaluation.

Problem
-------
Pynguin-generated tests contain:
  "# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
   # Please check them before you use them."

The LLM judge saw this comment in 77 comparisons (every Pynguin vs SLM pair),
meaning it was never blind to which test was machine-generated. This is an
internal validity threat affecting only the Pynguin rankings.

Fix
---
1. Load the original JSONL.
2. Identify the 77 affected records.
3. Strip the Pynguin authorship comment from code_a / code_b.
4. Re-run judge_pair_double_pass() with the cleaned code.
5. Patch those 77 records in place; leave all 186 SLM-vs-SLM records untouched.
6. Overwrite the JSONL (original backed up as .bak).
7. Recompute evaluation_statistics_full_factorial.json.

Usage (from repo root)
----------------------
python step3_modelling/repatch_pynguin_comparisons.py
"""

import json
import re
import os
import sys
import shutil

from tqdm import tqdm


# Paths
REPO_ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSONL_PATH = os.path.join(REPO_ROOT, "TestEval", "predictions_judgellm",
                          "pairwise_judgements_full_factorial.jsonl")
STATS_PATH = os.path.join(REPO_ROOT, "TestEval", "predictions_judgellm",
                          "evaluation_statistics_full_factorial.json")


# Import the judge function (runs dotenv + client init inside llm_as_judge)
sys.path.insert(0, REPO_ROOT)
from step3_modelling.llm_as_judge import judge_pair_double_pass  # noqa: E402


# Comment stripping
_PYNGUIN_RE = re.compile(
    r"#\s*Test cases automatically generated by Pynguin[^\n]*\n"
    r"#\s*Please check them before you use them\.[^\n]*\n?",
    re.IGNORECASE,
)
PYNGUIN_MARKER = "automatically generated by Pynguin"


def strip_pynguin_comment(code: str) -> str:
    """Remove the two-line Pynguin authorship comment and any resulting blank line."""
    cleaned = _PYNGUIN_RE.sub("", code)
    # Remove leading blank lines that the comment may have left
    return cleaned.lstrip("\n")



# Statistics recomputation (matches original stats file format)
def recompute_stats(records: list) -> dict:
    bias_counts:   dict[str, int] = {}
    winner_counts: dict[str, int] = {}
    for rec in records:
        bias   = rec.get("bias_status", "None")
        winner = rec.get("final_winner_model", "Unknown")
        bias_counts[bias]     = bias_counts.get(bias, 0) + 1
        winner_counts[winner] = winner_counts.get(winner, 0) + 1
    return {
        "total_comparisons":  len(records),
        "bias_analysis":      bias_counts,
        "winner_distribution": winner_counts,
    }


def main():
    # Load original records
    records: list[dict] = []
    with open(JSONL_PATH, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    print(f"Loaded {len(records)} total records from {JSONL_PATH}")

    # Identify affected records
    affected_indices = [
        i for i, rec in enumerate(records)
        if PYNGUIN_MARKER in rec.get("code_a", "")
        or PYNGUIN_MARKER in rec.get("code_b", "")
    ]
    print(f"Found {len(affected_indices)} Pynguin comparisons to re-run")
    if not affected_indices:
        print("Nothing to do — exiting.")
        return

    # Sanity-check: every affected record should involve Pynguin (Baseline)
    non_pynguin = [
        i for i in affected_indices
        if "Pynguin" not in records[i].get("model_a", "")
        and "Pynguin" not in records[i].get("model_b", "")
    ]
    if non_pynguin:
        print(f"WARNING: {len(non_pynguin)} affected records do NOT involve Pynguin model — inspect manually.")

    # --- Back up original JSONL -------------------------------------------------
    backup_path = JSONL_PATH + ".bak"
    shutil.copy2(JSONL_PATH, backup_path)
    print(f"Original backed up → {backup_path}")

    # --- Re-run affected comparisons --------------------------------------------
    failed_indices: list[int] = []

    for i in tqdm(affected_indices, desc="Re-judging (blind)"):
        rec = records[i]

        clean_a = strip_pynguin_comment(rec["code_a"])
        clean_b = strip_pynguin_comment(rec["code_b"])

        new_result = judge_pair_double_pass(
            task_id    = rec["task_id"],
            focal_code = rec["focal_code"],
            docstring  = rec.get("docstring", ""),
            model_a_name = rec["model_a"],
            code_a       = clean_a,
            model_b_name = rec["model_b"],
            code_b       = clean_b,
        )

        if new_result is None:
            print(f"\n  FAILED — kept original (biased): "
                  f"task={rec['task_id']}  {rec['model_a']} vs {rec['model_b']}")
            failed_indices.append(i)
            continue

        records[i] = new_result

    print(f"\nRe-run complete.  Success: {len(affected_indices) - len(failed_indices)} / {len(affected_indices)}")
    if failed_indices:
        print(f"WARNING: {len(failed_indices)} comparisons failed — original (biased) records retained.")

    # --- Write patched JSONL ----------------------------------------------------
    with open(JSONL_PATH, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(f"Wrote {len(records)} records → {JSONL_PATH}")

    # --- Recompute statistics ----------------------------------------------------
    stats = recompute_stats(records)
    with open(STATS_PATH, "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)
    print(f"Updated statistics → {STATS_PATH}")
    print(json.dumps(stats, indent=2))

    # --- Summary of outcome changes ---------------------------------------------
    print("\n--- Winner outcome changes (old → new) ---")
    old_records_map = {}
    with open(backup_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                r = json.loads(line)
                old_records_map[(r["task_id"], r["model_a"], r["model_b"])] = r

    changed = 0
    for i in affected_indices:
        if i in failed_indices:
            continue
        new = records[i]
        key = (new["task_id"], new["model_a"], new["model_b"])
        old = old_records_map.get(key)
        if old and old.get("final_winner_model") != new.get("final_winner_model"):
            changed += 1
            print(f"  task={new['task_id']:6}  {new['model_a']:45} vs Pynguin  "
                  f"{old['final_winner_model']} → {new['final_winner_model']}")

    print(f"\nTotal outcome changes: {changed} / {len(affected_indices) - len(failed_indices)}")
    if changed == 0:
        print("No winner changes — the comment bias did not affect decisions (good to report).")
    else:
        print("Winner changes detected — re-run analyze_judge_results.py to update rankings.")


if __name__ == "__main__":
    main()
